### ISSUE TITLE
Quick Action Name is Not shown

### ISSUE THREAD

**Issue by michaelkrnac** [osmandapp/OsmAnd-iOS#801] opened 2020-08-16 12:14 UTC
In the Quick Action Menu the Action Name Should be Shown. I have Many actions to  Show/Hide different POIs its very confusing without the Name .
![F5CE844A-133D-43F7-BDE2-70F2FEB4E038](https://user-images.githubusercontent.com/3944657/90333986-ae5deb80-dfca-11ea-8be3-d421f75e9904.jpeg)

**Comment by PaulStets** [comment] 2020-08-18 07:52
Duplicate of https://github.com/osmandapp/OsmAnd-iOS/issues/649. Will be fixed in the next release.

**Closed by PaulStets** 2020-08-18 07:52 UTC
