### ISSUE TITLE
Tracks are transparent

### ISSUE THREAD

**Issue by klecksi24** [osmandapp/OsmAnd-iOS#3660] opened 2024-05-01 20:15 UTC
Since update last week via Appstore: All tracks are transparent on the map (no coloured route line), although they should be visible. Only Start and finish point and direction is visible. Iphone 6s, IOS 15.8.2, Osmand 4.7.4.3
Same issue, if you want to create a track.

Is it possible to install an older version and where can i download the file? I always use Osmand, but without route line, it is not possible.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/168678996/963dd924-03df-4c3d-9edb-67edd1cfe39b"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by AleZan-italy** [comment] 2024-05-01 20:34
I've the same problem on my iPad 5 gen, running iOS 16.7.7 and OsmAnd Build: 4.7.3.10

**Comment by DmitryAlexei** [comment] 2024-05-01 21:47
It's a duplicate of https://github.com/osmandapp/OsmAnd-iOS/issues/3425. Hopefully, the fix will be available in the next release.

**Comment by AleZan-italy** [comment] 2024-05-02 06:56
OK. Thanks.

AZ
--
www.alessandrozanini.it


Il giorno mer 1 mag 2024 alle ore 23:47 DmitryAlexei <
***@***.***> ha scritto:

**Comment by tatobox** [comment] 2024-05-09 20:24
It was closed by #3425  and available in 4.7.5.5

**Closed** 2024-05-09 22:34 UTC
