### ISSUE TITLE
[UI] downloading progress bar overlaps if label is too long

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#2865] opened 2023-05-05 14:36 UTC
In OsmAnd 4.4.1, if the title of something being downloaded is too long, I get an UI bug on the progress bar :
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/59312735/236488527-305de873-6d17-45da-aec2-799e257fd42b.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  
I got the issue while downloading Armenia data

**Comment by Zirochkabila** [comment] 2023-05-08 15:07
@nabilys Try to update to 4.4.7 or TestFlight version

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/236860186-38199191-8305-4038-891f-75b77b826ce2.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by nabilys** [comment] 2023-05-09 06:20
I have limited data access so it’s difficult right now sorry… seems to happen on a specific combination :
-planning a route so navigation widgets are shown
-start downloading map
-put horizontal screen orientation 
-switch back to vertical screen orientation 
![IMG_3737](https://user-images.githubusercontent.com/59312735/237010663-b89fe492-e874-4790-b620-ac45ac3d1138.png)
![IMG_3738](https://user-images.githubusercontent.com/59312735/237010711-a068efad-bebd-4a9c-8ea1-3379c0eb31b2.png)
![IMG_3739](https://user-images.githubusercontent.com/59312735/237010720-afeae88b-e07e-440d-94f1-3154ed085464.png)

**Comment by Zirochkabila** [comment] 2023-05-09 10:26
@nabilys It seems that this bug has been fixed in the TestFlight version (or newer) - still can't reproduce 


https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/50c2c39f-0410-4a94-b0c4-ee0192d1f881

**Closed** 2023-06-04 16:51 UTC
