### ISSUE TITLE
GPX menu

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd-iOS#1621] opened 2021-11-19 10:36 UTC
Hello,

The GPX tracks improvements are excellent! 
Moving the GPX menu to the settings list would be easier and more accessible

![image](https://user-images.githubusercontent.com/79785663/142608904-1bd01699-d707-482a-9dc3-876279943e90.jpeg)

**Comment by dmpr0** [comment] 2022-06-15 08:59
Duplicate of https://github.com/osmandapp/OsmAnd-iOS/issues/1622. 
All these requests are linked to Drawer items and order customization.

**Closed by dmpr0** 2022-06-15 08:59 UTC
