### ISSUE TITLE
Route calculation makes the app crash - avoid parameters

### ISSUE THREAD

**Issue by matteoar1** [osmandapp/OsmAnd-iOS#3453] opened 2024-02-21 11:54 UTC
### Description

Calculating a 90 km route makes the app crash.
The only parameters I added are:
- Avoid paid roads;
- Avoid Highways.
I subscripted for the annual plan, I don't know if makes a difference in the app.

I also tried to change the language of the app but it didn't make difference.

### Steps to reproduce

1. In Menu → Configure profile (Boat, Driving, Walking or another one) → Navigation settings → Navigation type select select the two parameters (avoid paid roads and highways).
2. Calculate a route
3. wait for the app to crash.

### Actual result

The app crash.
I cannot use it.

https://github.com/osmandapp/OsmAnd/assets/146936781/13278b6c-b0e2-489f-b925-5228463bf00b

### Expected result

I know that the app calculate the route locally but I didn't expect problems with a 90kms route!
I just want calculate a route without highways!

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.6.1 (but I also tried the betas)
Android/iOS version: 17.2.1 (I'll update to 17.3.1 today)
Device model: iPhone 14 Pro
Crash-Logs: Attached
```
[feb 21, 2024 12_32.log](https://github.com/osmandapp/OsmAnd/files/14358915/feb.21.2024.12_32.log)
[feb 21, 2024 12_13.log](https://github.com/osmandapp/OsmAnd/files/14358916/feb.21.2024.12_13.log)
[feb 21, 2024 12_25.log](https://github.com/osmandapp/OsmAnd/files/14358918/feb.21.2024.12_25.log)
[feb 21, 2024 12_29.log](https://github.com/osmandapp/OsmAnd/files/14358919/feb.21.2024.12_29.log)
[Feb 21, 2024 12_47.log](https://github.com/osmandapp/OsmAnd/files/14359001/Feb.21.2024.12_47.log)

**Comment by matteoar1** [comment] 2024-02-27 11:36
Can someone help me please? I paid for the app and I'm not able to use it as planned.

**Comment by vshcherb** [comment] 2024-02-27 17:26
We reproduced the crash and going to fix it. Though as a quick workaround you can try different profile / parameters until we fix it.

**Comment by matteoar1** [comment] 2024-03-01 14:11
Hello, @vshcherb can you give me update? I contacted the support team but they won't give me my money back (that's absurd) nor a redeem code (absurd too) for the time I'm not able to use the app the way I want (the way I paid for!).
How much time should I wait in order to see the problem fixed? Thank you.

**Comment by matteoar1** [comment] 2024-03-01 14:14
@Chumva @EugeneZmeuk @alexey-pelykh @sonora

**Comment by RZR-UA** [comment] 2024-03-01 14:42
https://test.osmand.net/map/?start=45.553500,8.948560&finish=45.132290,9.556660&type=osmand&profile=motorcycle&params=motorcycle,avoid_toll,avoid_motorway,hhoff,nativerouting#10/45.3122/9.0376 no crash on current master branch via web map. Need to test in the nightly iOS App.

**Comment by RZR-UA** [comment] 2024-03-01 16:25
![Simulator Screenshot - iPhone 15 - 2024-03-01 at 18 17 35](https://github.com/osmandapp/OsmAnd-iOS/assets/90444451/1f34b0ff-deb5-4870-ac92-0f487c260eda)

![Simulator Screenshot - iPhone 15 - 2024-03-01 at 18 17 46](https://github.com/osmandapp/OsmAnd-iOS/assets/90444451/df9ff238-dd30-401d-bf2d-63393d58aa12)

![Simulator Screenshot - iPhone 15 - 2024-03-01 at 18 18 09](https://github.com/osmandapp/OsmAnd-iOS/assets/90444451/8925d15e-f602-4345-94e1-b4b38b4ca533)

**Comment by matteoar1** [comment] 2024-03-01 17:15
I cannot do it. My app crash. I tested even with the beta but it still crash.

**Comment by matteoar1** [comment] 2024-03-01 17:16
Are you doing it with the simulator??

**Comment by matteoar1** [comment] 2024-03-01 17:21
If you do it on the actual phone it will crash the app. Even with the latest beta.

**Comment by RZR-UA** [comment] 2024-03-01 17:35
> If you do it on the actual phone it will crash the app. Even with the latest beta.

Significant fix for car/moto routing was commited at Sun Feb 25 03:05:51 2024

Could you share the version and date of the latest beta you have tried?

Hopefully it should be fixed in builds after 26 Feb.

**Comment by matteoar1** [comment] 2024-03-01 19:28
I just tried right now and yes, it works for a 94km trip it works but if you change the destination for example "Piacenza" (trip long 112km!) it crashes. The app doesn't create crash log. The same problem.

https://github.com/osmandapp/OsmAnd-iOS/assets/146936781/2cedafc1-266a-45ac-871c-4680c5f7b811

[mar 01, 2024 20_14.log](https://github.com/osmandapp/OsmAnd-iOS/files/14465152/mar.01.2024.20_14.log)

![IMG_8962](https://github.com/osmandapp/OsmAnd-iOS/assets/146936781/11f27055-cf83-46a4-95ad-e8cf61cc5520)

**Comment by matteoar1** [comment] 2024-03-01 19:29
It is just a matter of distance?

**Comment by vshcherb** [comment] 2024-03-11 18:26
This new routing algorithm crash I don't think it's a crash out of memory.

**Comment by matteoar1** [comment] 2024-03-13 12:01
> ## This new routing algorithm crash I don't think it's a crash out of memory.
Enabling Developer plugin and using "Special Routing" is the solution. I don't know what it does, probably change the routing algorithm.

I tried to calculate the same route with the same profile (motorcycle, no tolls road, no  highways)"Special routing" turned on and off.

Route 90kms
With special routing on calculation took 4 seconds. (Video n°1)
With special routing off calculation took 2' 30". (Video n°2)

I tried the same with a 125kms route and(No video due to file dimensions):
With special routing on calculation took 9 seconds
With special routing off the app crashes.

I tried the same with a 700kms route and (no video):
With special routing on calculation took 10-20 seconds
With special routing off the app crashes.

https://github.com/osmandapp/OsmAnd-iOS/assets/146936781/5fa52a35-fdde-4fc9-a664-8c8001b56552
https://github.com/osmandapp/OsmAnd-iOS/assets/146936781/15d8ddb7-a8cd-4057-855e-ccb755f287ed

**Closed** 2024-03-16 15:24 UTC
Labels: routing, !

**Comment by DmitryAlexei** [comment] 2024-03-27 13:48
OsmAnd TestFlight 4.7.2.11 

The issue is no more reproducible 
> ... using motorbike profile with **Avoid Toll roads** and **Avoid Motorways** options enabled. No crash logs were generated profile - [Motorcycle.osf.txt](https://github.com/osmandapp/OsmAnd-iOS/files/14430952/Motorcycle.osf.txt) start - 45.55350° N, 8.94856° E finish - 45.13229° N, 9.55666° E

<table style="width:100%">
  </tr>
  <tr>
    <th>Settings</th>
    <th>Old routing</th>
    <th>New routing</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/cc02c8a7-4cf0-4133-bc8c-5620b1c2bef3"  width="300" height="auto"/> </th>
 <th><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/9a755c5d-602a-4637-ae20-12d88930f84b"  width="300" height="auto"/> </th>
  <th><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/de1615a5-b436-4e0c-aebe-8ad7ccd6cca2"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by matteoar1** [comment] 2024-06-05 10:00
The issue is still here. Please reopen the case. It is not possible to calculate a 90km road with no toll road and no motorways. That's absurd.
