### ISSUE TITLE
The issue with the tracks list in CarPlay

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1197] opened 2021-05-07 12:03 UTC
There are 3 tracks on the device and only one is visible on the list in Carplay. Other tracks are displaying on the CarPlay screen but not in the list when hitting Directions>tracks
https://user-images.githubusercontent.com/80623554/117447254-edabde00-af45-11eb-913b-6cd8bc7e649e.mov

**Comment by nnngrach** [comment] 2021-06-04 07:55
It looks like this bug is no longer being reproduced at the moment. Probably its cause was fixed by performing one of the previous tasks. I think the user can check in the nearest TestFilght to see if this bug still appears.

**Closed** 2021-06-04 07:56 UTC
