### ISSUE TITLE
Carplay view not centered

### ISSUE THREAD

**Issue by leochras** [osmandapp/OsmAnd-iOS#2028] opened 2022-06-14 20:36 UTC
Is it just me, or is the CarPlay view not centered when navigating? The normal "navigation" overlay is getting in the way of the path. Used with Osmand Testflight beta (4.2.2.2) on iPhone XR and Renault Zoe.
![WhatsApp Image 2022-06-14 at 22 30 23](https://user-images.githubusercontent.com/16163571/173683252-dbef8e55-7006-47bd-a0a7-8842076e02cb.jpeg)

**Comment by Raphty** [comment] 2022-06-17 06:16
My CarPlay looks way different. 

The OsmAnd app on mine is also weird though, I experience the "current position" off to the right and dead center there, so I almost see nothing of the way ahead... and a whole lot of what is happening to the left of me. 


FYI if you make a screenshot on your iPhone while CarPlay is activated it captures both screens and you can delete the phone one and crop the CarPlay one so it shows the thing you want and nothing more.

**Comment by leochras** [comment] 2022-06-17 08:35
> FYI if you make a screenshot on your iPhone while CarPlay is activated it captures both screens and you can delete the phone one and crop the CarPlay one so it shows the thing you want and nothing more.

Oh wow, I didn't know that 😅 

Maybe it has something to do with the way the "center" position is calculated, because this display is kind of unusual, because its in portrait mode.

**Comment by Zirochkabila** [comment] 2022-08-05 14:05
OsmAnd version 3.0 - The case was not reproduced.
As you can see from the screen recording - CarPlay automatically places the location in the centre of the screen.
Try calibrating your location using the compass on your smartphone before starting navigation on CarPlay and then starting navigation on CarPlay.
[Screen Recording 2022-08-05 at 17.00.59.mov.zip](https://github.com/osmandapp/OsmAnd-iOS/files/9269298/Screen.Recording.2022-08-05.at.17.00.59.mov.zip)

**Comment by leochras** [comment] 2022-08-07 14:45
Still not centered (OsmAnd 4.3.0)
![image](https://user-images.githubusercontent.com/16163571/183296607-632a5220-3d85-432e-92ad-9dbb3a22a376.png)

**Comment by PaulStets** [comment] 2022-08-08 07:22
The problem is in the method that determines LHT/RHT (- (void) enterNavigationMode)

**Comment by PaulStets** [comment] 2022-08-15 07:43
Should be fixed in the next TestFlight build. Please test it one it is out and let us know if it's fixed.

**Closed** 2022-08-15 07:43 UTC
Labels: ios-ui

**Comment by leochras** [comment] 2022-08-23 19:50
Thank you, that seems to be fixed now!

![image](https://user-images.githubusercontent.com/16163571/186242775-d855eae1-2411-4989-b8eb-ec298ff8c3d4.png)
