### ISSUE TITLE
Slow rendering 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd-ios#100] opened 2018-06-22 12:46 UTC
Map (topo style with contour lines) rendering is really slow on iPhone 7.

**Comment by salomvary** [comment] 2018-07-04 08:34
First of all, thanks for this great app!

I am having this issue too. It's not new, been experiencing this ever since I'm using OsmAnd (~2 years). It also does not always happen, sometimes the rendering speed is fine. Other times however redrawing the map takes *minutes* or never even finishes. It happens more often when I'm in the backcountry or mountains.

When the app is having rendering issues, the GPS precision often also drops to several kilometers radius. I verified this not being a signal reception problem by switching to other apps which are able to show the position with high precision the same time.

Hardware/software:
- iPhone SE
- iOS 11.4
- OsmAnd 2.1

I created a screen recording of the problem: https://youtu.be/ZR7YE8yyI1w

**Comment by michaelkrnac** [comment] 2018-07-16 06:18
Same Problem here. Thought it is because my iphone 6 is to slow.

I really love the app. Hopefully it will  become more reliable.

**Comment by vshcherb** [comment] 2018-07-16 13:59
We identified the issue is related to SRTM data (the contour lines), we are thinking about possible solutions.

**Comment by schwabse** [comment] 2018-10-13 02:04
Upvote. I do have the same issue with iPhone 6s and iOS 12. Can confirm that it is most likely the contour lines which render the app useless. Especially when zooming close in.

**Comment by sirvydasdagys** [comment] 2019-03-25 13:11
I have the same issue with iPhone 8 and iOS 12.1.4. Very annoying issue.

**Comment by PaulStets** [comment] 2019-06-08 11:06
This was fixed in 2.80 version.

**Closed by PaulStets** 2019-06-08 11:06 UTC
