### ISSUE TITLE
Live update do not show

### ISSUE THREAD

**Issue by Martin868** [osmandapp/OsmAnd-iOS#3890] opened 2024-08-02 19:03 UTC
I use live updates all the time because I edit osm. For a while now live update does not work. I have it enabled. I see the update files being downloaded. But the map never shows the edits. Rinnlatest app

**Comment by yuriiurshuliak** [comment] 2024-08-03 08:39
Duplicate of https://github.com/osmandapp/OsmAnd-iOS/issues/3887

**Closed** 2024-08-05 11:19 UTC
