### ISSUE TITLE
Some distances/elevations aren't rendered in Wikipedia articles

### ISSUE THREAD

**Issue by huonw** [osmandapp/OsmAnd-ios#180] opened 2018-11-29 12:56 UTC
It seems some distances in Wikipedia articles have a special markup, which makes certain articles about geographical features (e.g. mountains) much less useful. For instance, https://en.wikipedia.org/wiki/Huascar%C3%A1n#Geography lists the heights of Huascarán (tallest mountain in Peru):

> ## Geography
>
> The mountain has two distinct summits, the higher being the south one (Huascarán Sur) with an elevation of 6,768 metres (22,205 ft).[1] The north summit (Huascarán Norte) has an elevation of 6,654 metres (21,831 ft).[1] Both summits are separated by a saddle (called 'Garganta'). The core of Huascarán, like much of the Cordillera Blanca, consists of Cenozoic era granite.[4] 

However, the OSMAnd display of the article omits them:

![img_c0caace3d338-1](https://user-images.githubusercontent.com/1203825/49223172-1d2f9580-f432-11e8-9b9c-1777bd025ff0.jpeg)

It looks like this article, along with many others, is using a special markup for unit conversions:

```
The mountain has two distinct summits, the higher being the south one (Huascarán Sur) with an 
elevation of {{convert|6768|m|0}}.<ref name=h/> The north summit (Huascarán Norte) has an 
elevation of {{convert|6654|m|0}}.<ref name=h/>  Both summits are separated by a saddle (called 
'Garganta'). The core of Huascarán, like much of the Cordillera Blanca, consists of [[Cenozoic]] era 
[[granite]].<ref name="ricker">Ricker, John F., ''Yuraq Janka: Cordilleras Blanca and Rosko'', Alpine 
Club of Canada, 1977, {{ISBN|0-920330-04-5}}, after Wilson, Reyes, and Garayar, 1967.</ref>
```

OsmAnd: 2.40
iOS: 12.1

**Comment by PaulStets** [comment] 2019-04-23 07:27
Duplicate of https://github.com/osmandapp/Osmand/issues/5582. Was fixed with https://github.com/osmandapp/OsmAnd-tools/commit/de581a26c40e920f995b3f098b0f5921afcf5ddb

**Closed by PaulStets** 2019-04-23 07:27 UTC
