### ISSUE TITLE
Car navigation profile with less map clutter

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#3875] opened 2024-07-29 16:02 UTC
The LightRS map type is the most clean for car navigation, but it is still way too cluttered. In particular in urban areas where lots of roads intersect, the route line gets easily lost in many irrelevant items on the map, eg
- public transport stops including their text names are always shown, without an option to turn them off.
- power lines are always drawn but not interesting for driving
- many small paths are shown that  are not interesting if they are not part of the actual planned route.

Is there a custom profile available somewhere that optimizes a map type for car navigation? Or a way to implement a de-cluttered version for a user?

**Comment by DmitryAlexei** [comment] 2024-07-30 15:56
Duplicate of https://github.com/osmandapp/OsmAnd/issues/18894
Some of the changes are already implemented in the latest [TestFlight version](https://osmand.net/docs/versions/nightly_versions#testflight) in default OsmAnd map style with driving profile

**Closed** 2024-07-31 10:41 UTC
