### ISSUE TITLE
Bug of last update

### ISSUE THREAD

**Issue by macdinos** [osmandapp/OsmAnd-iOS#3991] opened 2024-09-07 16:22 UTC
### Description

Changes in Profile Appearance settings cannot bw saved and stored.

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/284a5166-3c17-4a41-af20-c3d78d7c8f11"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/2d32229d-8ee1-4950-9c92-23620a9ee43d"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Steps to reproduce

...

### Actual result

It shows only a white circle

### Expected result

...

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: Last update (August 2024)
Android/iOS version: iOs 15.8.3
Device model: iPhone 7
Crash-Logs: ?
```

**Comment by dmpr0** [comment] 2024-09-09 09:11
Duplicate of https://github.com/osmandapp/OsmAnd-iOS/issues/3927

**Closed by dmpr0** 2024-09-09 09:11 UTC
