### ISSUE TITLE
Not updated worldwide overview map (testflight 3.11)

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-ios#501] opened 2019-11-26 08:49 UTC
After an updated worldwide overview map this map is located "Updates" again.

![image](https://user-images.githubusercontent.com/44466116/69613115-0a01d680-1042-11ea-823d-6066e832889c.png)

**Comment by dmpr0** [comment] 2019-12-06 09:10
Duplicate of #477

**Closed by dmpr0** 2019-12-06 09:10 UTC
