### ISSUE TITLE
Water Rendering Issue - Istanbul

### ISSUE THREAD

**Issue by dmklinger** [osmandapp/OsmAnd-iOS#3444] opened 2024-02-20 15:12 UTC
cf: https://github.com/osmandapp/OsmAnd/issues/19141

Water rendering issue on land that appears to be iOS specific. Tested on an iPad Pro 4th Gen and iPhone 13 Pro. 

Exact location: https://www.openstreetmap.org/#map=16/41.0662/29.0130

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/25443497/6477cb41-81c1-414f-a05f-6391e6ec50f6"  width="400" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment] 2024-02-21 11:36
Duplicate of #[19141](https://github.com/osmandapp/OsmAnd/issues/19141)

**Closed** 2024-02-26 17:40 UTC
