### ISSUE TITLE
CarPlay - Map orientation keeps rotating after version 4.7.3.10 update

### ISSUE THREAD

**Issue by sanketgarade** [osmandapp/OsmAnd-iOS#3619] opened 2024-04-21 14:26 UTC
Map angle is set to direction of travel. In previous version this used to be observed as expected on CarPlay. But in the latest version (4.7.3.10) the map orients in the travel direction for some time and in a few seconds keeps on switching in different directions and returns to the travel direction intermittently. This keeps on repeating.

**Comment by DmitryAlexei** [comment] 2024-04-21 19:54
duplicate of https://github.com/osmandapp/OsmAnd-iOS/issues/3618

**Closed** 2024-04-23 14:02 UTC
